(define (problem strips-truck2)
   (:domain truck-strips)
   (:objects tampinese changi bedok package1 totruck)
   (:init (location tampinese)
          (location changi)
          (location bedok)
          (package package1)
          (truck totruck)
          (at-locy tampinese)
          (free totruck)
          (at package1 bedok))
   (:goal (and (at package1 changi))))