(define (problem strips-truck3)
   (:domain truck-strips)
   (:objects tampinese changi bedok package1 package2 totruck)
   (:init (location tampinese)
          (location changi)
          (location bedok)
          (package package1)
          (package package2)
          (truck totruck)
          (at-locy tampinese)
          (free totruck)
          (at package1 bedok)
          (at package2 changi))
   (:goal (and (at package1 changi)
               (at package2 bedok))))